# Generated by Django 2.1.15 on 2021-01-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='predicted_class',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='predicted_value',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
