# Generated by Django 2.1.15 on 2021-01-14 17:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='saved_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='saved_path',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.generate_file_path),
        ),
    ]
